spring:
  application:
    name: triplog
  profiles:
    active: local
    include: mail
  config:
    import: optional:file:.env[.properties]

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      add-mappings: false
